{{- if .Values.messagegateway.enabled -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: "message-gateway"
  labels:
    app: message-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: message-gateway
  template:
    metadata:
      labels:
        app: message-gateway
    spec:
      containers:
        - name: message-gateway
          image: "{{ .Values.messagegateway.image }}"
          ports:
            - containerPort: 9191
          imagePullPolicy: Always
          resources:
            limits:
              memory: "512M"
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 9191
            initialDelaySeconds: 120
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 9191
            initialDelaySeconds: 120
            periodSeconds: 30

          env:
            - name: spring.datasource.url
              value: "{{ .Values.messagegateway.DATASOURCE_URL }}"
            - name: MYSQL_USERNAME
              value: "{{ .Values.messagegateway.MYSQL_USERNAME }}"
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "messagegateway-secret"
                  key: "database-password"
            - name: "CALLBACKCONFIG_HOST"
              value: "{{ .Values.messagegateway.CALLBACKCONFIG_HOST }}"
            - name: "HOSTCONFIG_HOST"
              value: "{{ .Values.messagegateway.HOSTCONFIG_HOST }}"
            - name: "PROVIDERSOURCE_FROMDATABASE"
              value: "{{ .Values.messagegateway.PROVIDERSOURCE_FROMDATABASE }}"
            - name: "PROVIDERSOURCE_FROMYML"
              value: "{{ .Values.messagegateway.PROVIDERSOURCE_FROMYML }}"
            - name: "PROVIDERKEYS_TELERIVETAPIKEY"
              valueFrom:
                secretKeyRef:
                  name: "messagegateway-secret"
                  key: "api-key"
            - name: "PROVIDERKEYS_TELERIVETPROJECTID"
              valueFrom:
                secretKeyRef:
                  name: "messagegateway-secret"
                  key: "project-id"
          volumeMounts:
            - name: ph-ee-config
              mountPath: "/config"
      initContainers:
        - name: wait-db
          image: jwilder/dockerize
          imagePullPolicy: IfNotPresent
          args:
            - -timeout=120s
            - -wait
            - tcp://operationsmysql:3306
      volumes:
        - name: ph-ee-config
          configMap:
            name: ph-ee-config
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: message-gateway
  name: message-gateway
spec:
  ports:
    - name: port
      port: 80
      protocol: TCP
      targetPort: 9191
  selector:
    app: message-gateway
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Secret
metadata:
  name: messagegateway-secret
type: Opaque
data:
  api-key: "{{ .Values.messagegateway.secret.value.api_key | b64enc }}"
  project-id: "{{ .Values.messagegateway.secret.value.project_id | b64enc }}"
  database-password: {{ .Values.messagegateway.MYSQL_PASSWORD | b64enc }}
---
{{- if .Values.messagegateway.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: message-gateway
  annotations:
{{- if .Values.messagegateway.ingress.annotations }}
{{ toYaml .Values.messagegateway.ingress.annotations | indent 4 }}
{{- end }}
spec:
  rules:
    - host: "{{ .Values.messagegateway.hostname }}"
      http:
        paths:
          - path: /messages
            pathType: Prefix
            backend:
              service:
                name: message-gateway
                port: 
                  number: 80
  tls:
    - hosts:
        - "{{ .Values.wildcardhostname }}"
      secretName: "{{ .Values.tls }}"
{{- end }}

{{- end }}