{{- if .Values.roster_connector.enabled -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: "ph-ee-connector-ams-roster"
  labels:
    app: ph-ee-connector-ams-roster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ph-ee-connector-ams-roster
  template:
    metadata:
      labels:
        app: ph-ee-connector-ams-roster
      annotations:
        deployTime: "{{ .Values.deployTime }}"
    spec:
      containers:
        - name: ph-ee-connector-ams-roster
          image: "{{ .Values.roster_connector.image }}"
          ports:
            - containerPort: 5000
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 30
          env:
            - name: "SPRING_PROFILES_ACTIVE"
              value: "{{ .Values.roster_connector.SPRING_PROFILES_ACTIVE }}"
            - name: "ZEEBE_BROKER_CONTACTPOINT"
              value: "zeebe-zeebe-gateway:26500"
            - name: "AMS_LOCAL_ENABLED"
              value: "{{ .Values.roster_connector.ams.local.enabled }}"
            - name: "PESACORE_AUTH-HEADER"
              value: "{{ .Values.roster_connector.pesacore.auth_header }}"
            - name: "PESACORE_BASE-URL"
              value: "{{ .Values.roster_connector.pesacore.base_url }}"
          resources:
            limits:
              memory: "512M"

{{- end }}