apiVersion: apps/v1
kind: Deployment
metadata:
  name: "ph-ee-connector-channel"
  labels:
    app: ph-ee-connector-channel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ph-ee-connector-channel
  template:
    metadata:
      labels:
        app: ph-ee-connector-channel
      annotations:
{{- if .Values.channel.deployment.annotations }}
{{ toYaml .Values.channel.deployment.annotations | indent 8 }}
{{- end }}
    spec:
      containers:
        - name: ph-ee-connector-channel
          image: "{{ .Values.channel.image }}"
          ports:
            - containerPort: 5000
          imagePullPolicy: Always
          resources:
            limits:
              memory: "768M"
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 30
          env:
            - name: "SPRING_PROFILES_ACTIVE"
              value: "{{ .Values.channel.SPRING_PROFILES_ACTIVE }}"
            - name: "DFSPIDS"
              value: "{{ .Values.channel.DFSPIDS }}"
            - name: "TRANSACTION-ID-LENGTH"
              value: "{{ .Values.channel.transaction_id_length }}"
            - name: "MPESA_NOTIFICATION_SUCCESS_ENABLED"
              value: "{{ .Values.notifications.NOTIFICATION_SUCCESS_ENABLED }}"
            - name: "MPESA_NOTIFICATION_FAILURE_ENABLED"
              value: "{{ .Values.notifications.NOTIFICATION_FAILURE_ENABLED }}"
            - name:  "LOGGING_LEVEL_ROOT"
              value: "{{ .Values.channel.LOGGING_LEVEL_ROOT }}"
          volumeMounts:
            - name: ph-ee-config
              mountPath: "/config"
      volumes:
        - name: ph-ee-config
          configMap:
            name: ph-ee-config

---
{{- if .Values.channel.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ph-ee-connector-channel
  annotations:
{{- if .Values.channel.ingress.annotations }}
{{ toYaml .Values.channel.ingress.annotations | indent 4 }}
{{- end }}
spec:
  rules:
    - host: "{{ .Values.channel.hostname }}"
      http:
        paths:
        - path: /channel
          pathType: Prefix
          backend:
            service:
              name: ph-ee-connector-channel
              port: 
                number: 80
  tls:
    - hosts:
        - "{{ .Values.wildcardhostname }}"
      secretName: "{{ .Values.tls }}"
{{- end }}

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ph-ee-connector-channel
  name: ph-ee-connector-channel
spec:
  ports:
    - name: port
      port: 80
      protocol: TCP
      targetPort: 5000
  selector:
    app: ph-ee-connector-channel
  sessionAffinity: None
  type: ClusterIP
