{{- if .Values.operations.enabled -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ph-ee-importer-es
  labels:
    app: ph-ee-importer-es
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ph-ee-importer-es
  template:
    metadata:
      labels:
        app: ph-ee-importer-es
      annotations:
{{- if .Values.importer_es.deployment.annotations }}
{{ toYaml .Values.importer_es.deployment.annotations | indent 8 }}
{{- end }}
    spec:
      containers:
        - name: ph-ee-importer-es
          image: "{{ .Values.importer_es.image }}"
          imagePullPolicy: Always
          resources:
            limits:
              memory: "512M"

{{- end }}
