apiVersion: apps/v1
kind: Deployment
metadata:
  name: "ph-ee-zeebe-ops"
  labels:
    app: ph-ee-zeebe-ops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ph-ee-zeebe-ops
  template:
    metadata:
      labels:
        app: ph-ee-zeebe-ops
      annotations:
{{- if .Values.zeebe_ops.deployment.annotations }}
{{ toYaml .Values.zeebe_ops.deployment.annotations | indent 8 }}
{{- end }}
    spec:
      containers:
        - name: ph-ee-zeebe-ops
          image: "{{ .Values.zeebe_ops.image }}"
          imagePullPolicy: Always
          resources:
            limits:
              memory: "512M"
          ports:
            - containerPort: 5000
          env:
            - name: "ZEEBE_BROKER_CONTACTPOINT"
              value: "zeebe-zeebe-gateway:26500"
---
{{- if .Values.zeebe_ops.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ph-ee-zeebe-ops
  annotations:
{{- if .Values.zeebe_ops.ingress.annotations }}
{{ toYaml .Values.zeebe_ops.ingress.annotations | indent 4 }}
{{- end }}

spec:
  rules:
    - host: "{{ .Values.zeebe_ops.hostname }}"
      http:
        paths:
          - path: /zeebeops
            pathType: Prefix
            backend:
              service:
                name: ph-ee-zeebe-ops
                port: 
                  number: 80
  tls:
    - hosts:
        - "{{ .Values.wildcardhostname }}"
      secretName: "{{ .Values.tls }}"
{{- end }}

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ph-ee-zeebe-ops
  name: ph-ee-zeebe-ops
spec:
  ports:
    - name: port
      port: 80
      protocol: TCP
      targetPort: 5000
  selector:
    app: ph-ee-zeebe-ops
  sessionAffinity: None
  type: ClusterIP