dependencies:
- name: zeebe-cluster-helm
  repository: https://helm.camunda.io
  version: 1.0.0
- name: camunda-platform
  repository: https://helm.camunda.io
  version: 8.0.13
  condition: "operate.enabled"
- name: elasticsearch
  repository: http://helm.elastic.co
  version: 7.16.3
- name: kibana
  repository: http://helm.elastic.co
  version: 7.16.3
  condition: "kibana.enabled"
- name: mysql
  version: 8.8.23
  repository: "https://charts.bitnami.com/bitnami"
  alias: operationsmysql
  condition: "operations.mysql.enabled"

