zeebe-cluster-helm:
  global:
    zeebe: "zeebe-zeebe"
    elasticsearch:
      host: "zeebe-elasticsearch"

  image:
    repository: camunda/zeebe
    tag: 1.1.0

  clusterSize: "1"
  partitionCount: "1"
  replicationFactor: "1"
  cpuThreadCount: "2"
  ioThreadCount: "2"
  pvcSize: "10Gi"
  pvcAccessModes: [ "ReadWriteOnce" ]

  resources:
    requests:
      cpu: 100m

  env:
#    - name: ZEEBE_BROKER_BACKPRESSURE_ENABLED
#      value: "false"
    - name: ZEEBE_BROKER_EXECUTION_METRICS_EXPORTER_ENABLED
      value: "true"
#    - name: ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_CLASSNAME
#      value: "hu.dpc.rt.kafkastreamer.exporter.NoOpExporter"
    - name: ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_JARPATH
      value: "/exporters/ph-ee-kafka-exporter.jar"
    - name: ZEEBE_BROKER_EXPORTERS_KAFKA_JARPATH
      value: "/exporters/ph-ee-kafka-exporter.jar"
    - name: ZEEBE_BROKER_EXPORTERS_KAFKA_CLASSNAME
      value: "hu.dpc.rt.kafkastreamer.exporter.KafkaExporter"
    - name: ZEEBE_BROKER_BACKPRESSURE_VEGAS_INITIALLIMIT
      value: "1000"
    - name: ZEEBE_BROKER_BACKPRESSURE_VEGAS_ALPHA
      value: "2"
    - name: ZEEBE_BROKER_BACKPRESSURE_VEGAS_BETA
      value: "8"

  gateway:
    replicas: 1
    logLevel: warn
    env:
      - name: ZEEBE_GATEWAY_THREADS_MANAGEMENTTHREADS
        value: "4"
      - name: ZEEBE_GATEWAY_MONITORING_ENABLED
        value: "true"

  # zeebe's dependencies
  elasticsearch:
    enabled: false
    fullnameOverride: "zeebe-elasticsearch"
    clusterName: "zeebe-elasticsearch"

  kibana:
    enabled: false
    fullnameOverride: "zeebee-kibana"
    elasticsearchHosts: "http://zeebe-elasticsearch:9200/"

  prometheus:
    enabled: false

  extraInitContainers: |
    - name: init-ph-ee-kafka-exporter
      image: busybox:1.28
      command: ['/bin/sh', '-c']
      args: ['wget -O /exporters/ph-ee-kafka-exporter.jar "https://paymenthub-ee-dev.s3.us-east-2.amazonaws.com/jars/exporter-1.0.0-SNAPSHOT.jar"; ls -al /exporters/']
      volumeMounts:
      - name: exporters
        mountPath: /exporters/

# payment hub Operate, ES and Kibana
zeebe-operate-helm:
  enabled: false
  image:
    repository: camunda/operate
    tag: 1.1.0
  fullnameOverride: "zeebe-operate"
  global:
    zeebe: "zeebe-zeebe"
    elasticsearch:
      host: "zeebe-elasticsearch"
      clusterName: "zeebe-elasticsearch"

elasticsearch:
  enabled: false
  imageTag: 7.13.2
  replicas: 1
  fullnameOverride: "ph-ee-elasticsearch"
  clusterName: "ph-ee-elasticsearch"
  minimumMasterNodes: 1

kibana:
  enabled: false
  imageTag: 7.13.2
  fullnameOverride: "ph-ee-kibana"
  elasticsearchHosts: "http://ph-ee-elasticsearch:9200/"

channel:
  enabled: false
  replicas: 1
  image: ""
  imagePullPolicy: "Always"
  SPRING_PROFILES_ACTIVE: ""
  LOGGING_LEVEL_ROOT: "INFO"
  TRANSACTION_ID_LENGTH: 20
  DFSPIDS: ""
  hostname: ""
  limits:
    memory: "768M"
    cpu: 4
  requests:
    memory: "768M"
    cpu: 4
  ingress:
    enabled: true
    annotations: {}
    backend: {}
  deployment:
    annotations: {}

operations:
  enabled: false

ingress:
  apiversion: "networking.k8s.io/v1"

deployment:
  apiversion: "apps/v1"

service:
  apiversion: "v1"

secret:
  apiversion: "v1"

configmap:
  apiversion: "v1"

operationsmysql:
  fullnameOverride: "operationsmysql"
  image:
      tag: "5.7"
      debug: false
  auth:
    database: ""
    username: ""
    password: ""
    rootPassword: ""

ph_ee_connector_ams_mifos:
  enabled: false
  replicas: 1
  image: ""
  imagePullPolicy: "Always"
  SPRING_PROFILES_ACTIVE: ""
  limits:
    memory: "512M"
    cpu: 4
  requests:
    memory: "512M"
    cpu: 4
  deployment:
    annotations: {}

ph_ee_connector_mojaloop:
  enabled: false
  replicas: 1
  image: ""
  imagePullPolicy: "Always"
  SPRING_PROFILES_ACTIVE: ""
  limits:
    memory: "512M"
    cpu: 4
  requests:
    memory: "512M"
    cpu: 4
  deployment:
    annotations: {}

operations_app:
  enabled: false
  replicas: 1
  image: ""
  imagePullPolicy: "Always"
  SPRING_PROFILES_ACTIVE: ""
  LOGGING_LEVEL_ROOT: "INFO"
  hostname: ""
  tenants: ""
  token_client_channel_secret: ""
  datasource:
    username: ""
    password: ""
    host: ""
    port: 3306
    schema: ""
  limits:
    memory: "512M"
    cpu: 4
  requests:
    memory: "512M"
    cpu: 4
  ingress:
    enabled: true
    annotations: {}
    backend: {}
  deployment:
    annotations: {}

operations_web:
  enabled: false
  replicas: 1
  image: ""
  imagePullPolicy: "Always"
  hostname: ""
  path: "/"
  webhost: ""
  limits:
    memory: "512M"
    cpu: 4
  requests:
    memory: "512M"
    cpu: 4
  ingress:
    enabled: true
    annotations: {}
    backend: {}
  deployment:
    annotations: {}

identity:
  hostname: ""

mpesa:
  enabled: false
  replicas: 1
  image: ""
  imagePullPolicy: "Always"
  SPRING_PROFILES_ACTIVE: ""
  LOGGING_LEVEL_ROOT: "INFO"
  hostname: ""
  zeebe_broker_contactpoint: ""
  tenant: ""
  callback_host: ""
  business_short_code: ""
  till_number: ""
  retry_count: 1
  safaricom:
    auth_host: ""
    api_host: ""
  limits:
    memory: "512M"
    cpu: 4
  requests:
    memory: "512M"
    cpu: 4
  ingress:
    enabled: true
    annotations: {}
    backend: {}
  deployment:
    annotations: {}
  safaricom:
    auth_host: ""
  secret:
    name: ""
    key:
      auth_client_key: ""

roster_connector: 
  enabled: false
  replicas: 1
  image: ""
  imagePullPolicy: "Always"
  SPRING_PROFILES_ACTIVE: ""
  containerPort: 5000
  limits:
    memory: "512M"
    cpu: 4
  requests:
    memory: "512M"
    cpu: 4
  ams:
    local:
      enabled: ""
  pesacore:
    auth_header: ""
  deployment:
    annotations: {}

messagegateway:
  enabled: false
  replicas: 1
  image: ""
  imagePullPolicy: "Always"
  LOGGING_LEVEL_ROOT: "INFO"
  hostname: ""
  CALLBACKCONFIG_HOST: "ph-ee-connector-notifications"
  HOSTCONFIG_HOST: ""
  MYSQL_USERNAME: "mifos"
  MYSQL_PASSWORD: "password"
  DATASOURCE_URL: ""
  PROVIDERSOURCE_FROMDATABASE: ""
  PROVIDERSOURCE_FROMYML: ""
  limits:
    memory: "512M"
    cpu: 4
  requests:
    memory: "512M"
    cpu: 4
  ingress:
    enabled: true
    annotations: {}
    backend: {}
  secret:
    name: ""
    key:
      telerivet_api_key: ""
  deployment:
    annotations: {}

notifications:
  enabled: false
  replicas: 1
  image: ""
  imagePullPolicy: "Always"
  SPRING_PROFILES_ACTIVE: ""
  LOGGING_LEVEL_ROOT: "INFO"
  hostname: ""
  zeebe_broker_contactpoint: ""
  NOTIFICATION_LOCAL_HOST: ""
  MESSAGEGATEWAYCONFIG_HOST: ""
  NOTIFICATION_SUCCESS_ENABLED: false
  NOTIFICATION_FAILURE_ENABLED: false
  hostconfig:
    host: ""
    port: ""
  limits:
    memory: "512M"
    cpu: 4
  requests:
    memory: "512M"
    cpu: 4
  ingress:
    enabled: true
    annotations: {}
    backend: {}
  deployment:
    annotations: {}

zeebe_ops:
  enabled: false
  replicas: 1
  image: ""
  imagePullPolicy: "Always"
  SPRING_PROFILES_ACTIVE: ""
  LOGGING_LEVEL_ROOT: "INFO"
  hostname: ""
  zeebe_broker_contactpoint: ""
  tenants: ""
  limits:
    memory: "512M"
    cpu: 4
  requests:
    memory: "512M"
    cpu: 4
  ingress:
    enabled: true
    annotations: {}
    backend: {}
  deployment:
    annotations: {}

importer_es:
  replicas: 1
  image: ""
  imagePullPolicy: "Always"
  limits:
    memory: "512M"
    cpu: 4
  requests:
    memory: "512M"
    cpu: 4

kafka:
  enabled: false
  replicas: 1
  image: ""
  imagePullPolicy: "Always"
  advertised:
    host: ""
    port: ""
  limits:
    memory: "512M"
    cpu: 4
  requests:
    memory: "512M"
    cpu: 4
  deployment:
    annotations: {}

importer_rdbms:
  enabled: false
  replicas: 1
  image: ""
  imagePullPolicy: "Always"
  LOGGING_LEVEL_ROOT: "INFO"
  datasource:
      username: ""
      password: ""
      host: ""
      port: 3306
      schema: ""
  limits:
    memory: "512M"
    cpu: 4
  requests:
    memory: "512M"
    cpu: 4
  deployment:
    annotations: {}

connector_bulk:
  enabled: false
  replicas: 1
  image: ""
  imagePullPolicy: "Always"
  SPRING_PROFILES_ACTIVE: ""
  limits:
    memory: "512M"
    cpu: 4
  requests:
    memory: "512M"
    cpu: 4
  deployment:
    annotations: {}

ph_ee_connector_gsma:
  enabled: false
  replicas: 1
  image: ""
  imagePullPolicy: "Always"
  SPRING_PROFILES_ACTIVE: ""
  limits:
    memory: "512M"
    cpu: 4
  requests:
    memory: "512M"
    cpu: 4
  deployment:
    annotations: {}

ph_ee_connector_slcb:
  enabled: false
  replicas: 1
  image: ""
  imagePullPolicy: "Always"
  SPRING_PROFILES_ACTIVE: ""
  limits:
    memory: "512M"
    cpu: 4
  requests:
    memory: "512M"
    cpu: 4
  deployment:
    annotations: {}

wildcardhostname: ""

tls: "" 