
zeebe-cluster-helm:
  global:
    zeebe: "zeebe-zeebe"
    elasticsearch:
      host: "zeebe-elasticsearch"

  image:
    repository: camunda/zeebe
    tag: 1.1.0

  clusterSize: "1"
  partitionCount: "1"
  replicationFactor: "1"
  cpuThreadCount: "2"
  ioThreadCount: "2"
  pvcSize: "10Gi"
  pvcAccessModes: [ "ReadWriteOnce" ]

  resources:
    requests:
      cpu: 100m

  env:
#    - name: ZEEBE_BROKER_BACKPRESSURE_ENABLED
#      value: "false"
    - name: ZEEBE_BROKER_EXECUTION_METRICS_EXPORTER_ENABLED
      value: "true"
#    - name: ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_CLASSNAME
#      value: "hu.dpc.rt.kafkastreamer.exporter.NoOpExporter"
    - name: ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_JARPATH
      value: "/exporters/ph-ee-kafka-exporter.jar"
    - name: ZEEBE_BROKER_EXPORTERS_KAFKA_JARPATH
      value: "/exporters/ph-ee-kafka-exporter.jar"
    - name: ZEEBE_BROKER_EXPORTERS_KAFKA_CLASSNAME
      value: "hu.dpc.rt.kafkastreamer.exporter.KafkaExporter"
    - name: ZEEBE_BROKER_BACKPRESSURE_VEGAS_INITIALLIMIT
      value: "1000"
    - name: ZEEBE_BROKER_BACKPRESSURE_VEGAS_ALPHA
      value: "2"
    - name: ZEEBE_BROKER_BACKPRESSURE_VEGAS_BETA
      value: "8"

  gateway:
    replicas: 1
    logLevel: warn
    env:
      - name: ZEEBE_GATEWAY_THREADS_MANAGEMENTTHREADS
        value: "4"
      - name: ZEEBE_GATEWAY_MONITORING_ENABLED
        value: "true"

  # zeebe's dependencies
  elasticsearch:
    enabled: false
    fullnameOverride: "zeebe-elasticsearch"
    clusterName: "zeebe-elasticsearch"

  kibana:
    enabled: false
    fullnameOverride: "zeebee-kibana"
    elasticsearchHosts: "http://zeebe-elasticsearch:9200/"

  prometheus:
    enabled: false

  extraInitContainers: |
    - name: init-ph-ee-kafka-exporter
      image: busybox:1.28
      command: ['/bin/sh', '-c']
      args: ['wget -O /exporters/ph-ee-kafka-exporter.jar "https://paymenthub-ee-dev.s3.us-east-2.amazonaws.com/jars/exporter-1.0.0-SNAPSHOT.jar"; ls -al /exporters/']
      volumeMounts:
      - name: exporters
        mountPath: /exporters/

# payment hub Operate, ES and Kibana
zeebe-operate-helm:
  enabled: false
  image:
    repository: camunda/operate
    tag: 1.1.0
  fullnameOverride: "zeebe-operate"
  global:
    zeebe: "zeebe-zeebe"
    elasticsearch:
      host: "zeebe-elasticsearch"
      clusterName: "zeebe-elasticsearch"

elasticsearch:
  enabled: false
  imageTag: 7.13.2
  replicas: 1
  fullnameOverride: "ph-ee-elasticsearch"
  clusterName: "ph-ee-elasticsearch"
  minimumMasterNodes: 1

kibana:
  enabled: false
  imageTag: 7.13.2
  fullnameOverride: "ph-ee-kibana"
  elasticsearchHosts: "http://ph-ee-elasticsearch:9200/"

channel:
  enabled: false
  DFSPIDS: ""
  SPRING_PROFILES_ACTIVE: ""
  hostname: ""
  image: ""
  ingress:
    enabled: true
    annotations: {}
  deployment:
    annotations: {}

operations:
  enabled: false

ingress:
  apiversion: "networking.k8s.io/v1"

operationsmysql:
  fullnameOverride: "operationsmysql"
  image:
      tag: "5.7"
      debug: false
  auth:
    database: ""
    username: ""
    password: ""
    rootPassword: ""

ph_ee_connector_ams_mifos:
  enabled: false
  SPRING_PROFILES_ACTIVE: ""

ph_ee_connector_mojaloop:
  enabled: false
  SPRING_PROFILES_ACTIVE: ""

operations_app:
  enabled: false
  SPRING_PROFILES_ACTIVE: ""
  hostname: ""
  datasource:
    username: ""
    password: ""
    host: ""
    port: 3306
    schema: ""
  image: ""
  ingress:
    enabled: true
    annotations: {}
  deployment:
    annotations: {}

mpesa:
  enabled: false
  SPRING_PROFILES_ACTIVE: ""
  image: ""
  hostname: ""
  ingress:
    enabled: true
    annotations: {}
  deployment:
    annotations: {}
  safaricom:
    auth_host: ""
  secret:
    name: ""
    key:
      auth_client_key: ""

roster_connector: 
  enabled: false
  SPRING_PROFILES_ACTIVE: ""
  image: ""
  ams:
    local:
      enabled: ""
  pesacore:
    auth_header: ""
  deployment:
    annotations: {}

messagegateway:
  enabled: false
  image: ""
  hostname: ""
  ingress:
    enabled: true
    annotations: {}
  secret:
    name: ""
    key:
      telerivet_api_key: ""
  deployment:
    annotations: {}

notifications:
  enabled: false
  SPRING_PROFILES_ACTIVE: ""
  image: ""
  hostname: ""
  ingress:
    enabled: true
    annotations: {}
  deployment:
    annotations: {}

zeebe_ops:
  enabled: false
  SPRING_PROFILES_ACTIVE: ""
  hostname: ""
  ingress:
    enabled: true
    annotations: {}
  deployment:
    annotations: {}

importer_es:
  image: ""

kafka:
  enabled: false
  deployment:
    annotations: {}

importer_rdbms:
  enabled: false
  image: ""
  datasource:
      username: ""
      password: ""
      host: ""
      port: 3306
      schema: ""
  deployment:
    annotations: {}

connector_bulk:
  enabled: false
  SPRING_PROFILES_ACTIVE: ""
  deployment:
    annotations: {}

ph_ee_connector_gsma:
  enabled: false
  SPRING_PROFILES_ACTIVE: ""
  deployment:
    annotations: {}