zeebe:
    broker:
      contactpoint: "zeebe-zeebe-gateway:26500"

zeebe-cluster-helm:
  global:
    zeebe: "zeebe-zeebe"
    elasticsearch:
      host: "ph-ee-elasticsearch"

  image:
    repository: camunda/zeebe
    tag: 1.1.0

  clusterSize: "1"
  partitionCount: "1"
  replicationFactor: "1"
  cpuThreadCount: "2"
  ioThreadCount: "2"
  pvcSize: "10Gi"
  pvcAccessModes: [ "ReadWriteOnce" ]

  resources:
    requests:
      cpu: 100m

  env:
#    - name: ZEEBE_BROKER_BACKPRESSURE_ENABLED
#      value: "false"
    - name: ZEEBE_BROKER_EXECUTION_METRICS_EXPORTER_ENABLED
      value: "true"
    - name: ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_CLASSNAME
      value: "hu.dpc.rt.kafkastreamer.exporter.NoOpExporter"
    - name: ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_JARPATH
      value: "/exporters/ph-ee-kafka-exporter.jar"
    - name: ZEEBE_BROKER_EXPORTERS_KAFKA_JARPATH
      value: "/exporters/ph-ee-kafka-exporter.jar"
    - name: ZEEBE_BROKER_EXPORTERS_KAFKA_CLASSNAME
      value: "hu.dpc.rt.kafkastreamer.exporter.KafkaExporter"
    - name: ZEEBE_BROKER_BACKPRESSURE_VEGAS_INITIALLIMIT
      value: "1000"
    - name: ZEEBE_BROKER_BACKPRESSURE_VEGAS_ALPHA
      value: "2"
    - name: ZEEBE_BROKER_BACKPRESSURE_VEGAS_BETA
      value: "8"
    - name: ZEEBE_BROKER_EXPORTERS_KAFKA_ARGS_INDEX_EVENT
      value: 'true'
    - name: ZEEBE_BROKER_EXPORTERS_KAFKA_ARGS_INDEX_VARIABLE
      value: 'true'
    - name: ZEEBE_BROKER_EXPORTERS_KAFKA_ARGS_INDEX_PROCESSINSTANCE
      value: 'true'
    - name: ZEEBE_BROKER_EXPORTERS_KAFKA_ARGS_INDEX_PROCESS
      value: 'true'
    - name: ZEEBE_BROKER_EXPORTERS_KAFKA_ARGS_INDEX_INCIDENT
      value: 'true'
    - name: ZEEBE_BROKER_EXPORTERS_KAFKA_ARGS_INDEX_DEPLOYMENT
      value: 'false'
    - name: ZEEBE_BROKER_EXPORTERS_KAFKA_ARGS_INDEX_ERROR
      value: 'false'
    - name: ZEEBE_BROKER_EXPORTERS_KAFKA_ARGS_INDEX_JOB
      value: 'false'
    - name: ZEEBE_BROKER_EXPORTERS_KAFKA_ARGS_INDEX_VARIABLEDOCUMENT
      value: 'false'
    - name: ZEEBE_BROKER_EXPORTERS_KAFKA_ARGS_INDEX_WORKFLOWINSTANCE
      value: 'false'
    - name: ZEEBE_BROKER_EXPORTERS_KAFKA_ARGS_INDEX_CREATETEMPLATE
      value: 'false'


  gateway:
    replicas: 1
    logLevel: warn
    env:
      - name: ZEEBE_GATEWAY_THREADS_MANAGEMENTTHREADS
        value: "4"
      - name: ZEEBE_GATEWAY_MONITORING_ENABLED
        value: "true"

  # zeebe's dependencies
  elasticsearch:
    enabled: false
    fullnameOverride: "zeebe-elasticsearch"
    clusterName: "zeebe-elasticsearch"

  kibana:
    enabled: false
    fullnameOverride: "zeebee-kibana"
    elasticsearchHosts: "http://zeebe-elasticsearch:9200/"

  prometheus:
    enabled: false

  extraInitContainers: |
    - name: init-ph-ee-kafka-exporter
      image: busybox:1.28
      command: ['/bin/sh', '-c']
      args: ['wget -O /exporters/ph-ee-kafka-exporter.jar "https://paymenthub-ee-dev.s3.us-east-2.amazonaws.com/jars/exporter-1.0.0-SNAPSHOT.jar"; ls -al /exporters/']
      volumeMounts:
      - name: exporters
        mountPath: /exporters/

# payment hub Operate, ES and Kibana
zeebe-operate-helm:
  enabled: false
  image:
    repository: camunda/operate
    tag: 1.1.0
  fullnameOverride: "zeebe-operate"
  global:
    zeebe: "zeebe-zeebe"
    elasticsearch:
      host: "zeebe-elasticsearch"
      clusterName: "zeebe-elasticsearch"

elasticsearch:
  enabled: true
  imageTag: 7.16.3
  replicas: 1
  fullnameOverride: "ph-ee-elasticsearch"
  clusterName: "ph-ee-elasticsearch"
  minimumMasterNodes: 1

kibana:
  enabled: true
  imageTag: 7.16.3
  fullnameOverride: "ph-ee-kibana"
  elasticsearchHosts: "http://ph-ee-elasticsearch:9200/"

channel:
  enabled: true
  replicas: 1
  image: ""
  imageTag: "v1.0.0"
  imagePullPolicy: "Always"
  SPRING_PROFILES_ACTIVE: ""
  LOGGING_LEVEL_ROOT: "INFO"
  TRANSACTION_ID_LENGTH: 20
  DFSPIDS: ""
  hostname: ""
  limits:
    memory: "768M"
    cpu: "500m"
  requests:
    memory: "768M"
    cpu: "100m"
  ingress:
    enabled: true
    path: "/channel"
    annotations: {}
    backend: {}
  deployment:
    annotations: {}

operations:
  enabled: true
  mysql:
    enabled: true

ingress:
  apiversion: "networking.k8s.io/v1"

deployment:
  apiversion: "apps/v1"

service:
  apiversion: "v1"

secret:
  apiversion: "v1"

configmap:
  apiversion: "v1"

operationsmysql:
  fullnameOverride: "operationsmysql"
  image:
      tag: "5.7"
      debug: false
  auth:
      database: "tenants"
      username: "mifos"
      password: "password"
      rootPassword: "4ET6ywqlGt"
  initdbScripts:
      setup.sql: |-
        CREATE DATABASE IF NOT EXISTS phdefault;
        CREATE DATABASE IF NOT EXISTS messagegateway;
        GRANT ALL ON *.* TO 'root'@'%';
        GRANT ALL PRIVILEGES ON messagegateway.* TO 'mifos';
        GRANT ALL PRIVILEGES ON phdefault.* TO 'mifos';

ph_ee_connector_ams_mifos:
  enabled: false
  replicas: 1
  image: ""
  imageTag: "v1.0.0"
  imagePullPolicy: "Always"
  SPRING_PROFILES_ACTIVE: ""
  limits:
    memory: "512M"
    cpu: "500m"
  requests:
    memory: "512M"
    cpu: "100m"
  deployment:
    annotations: {}

ph_ee_connector_mojaloop:
  enabled: false
  replicas: 1
  image: ""
  imageTag: "v1.0.0"
  imagePullPolicy: "Always"
  SPRING_PROFILES_ACTIVE: ""
  limits:
    memory: "512M"
    cpu: "500m"
  requests:
    memory: "512M"
    cpu: "100m"
  deployment:
    annotations: {}

operations_app:
  enabled: true
  replicas: 1
  image: ""
  imageTag: "v1.0.2"
  imagePullPolicy: "Always"
  SPRING_PROFILES_ACTIVE: ""
  LOGGING_LEVEL_ROOT: "INFO"
  hostname: ""
  tenants: ""
  token_client_channel_secret: ""
  datasource:
      username: "mifos"
      password: "password"
      host: "operationsmysql"
      port: 3306
      schema: "tenants"
  limits:
    memory: "512M"
    cpu: "500m"
  requests:
    memory: "512M"
    cpu: "100m"
  ingress:
    enabled: false
    path: "/opsapp"
    annotations: {}
    backend: {}
  deployment:
    annotations: {}

operations_web:
  enabled: true
  replicas: 1
  image: ""
  imageTag: "v1.1.2"
  imagePullPolicy: "Always"
  hostname: ""
  webhost: ""
  limits:
    memory: "512M"
    cpu: "500m"
  requests:
    memory: "512M"
    cpu: "100m"
  ingress:
    enabled: false
    path: "/"
    annotations: {}
    backend: {}
  deployment:
    annotations: {}

identity:
  hostname: ""

mpesa:
  enabled: false
  replicas: 1
  image: ""
  imageTag: "v1.1.5"
  imagePullPolicy: "Always"
  SPRING_PROFILES_ACTIVE: ""
  LOGGING_LEVEL_ROOT: "INFO"
  hostname: ""
  zeebe_broker_contactpoint: "zeebe-zeebe-gateway:26500"
  zeebe_init_transfer_wait_timer: 10
  tenant: ""
  callback_host: ""
  accounts:
    default:
      name: "default"
      business_short_code: "7385028"
      till: "1234567"
      auth_host: "https://sandbox.safaricom.co.ke/oauth/v1/generate"
      api_host: "https://sandbox.safaricom.co.ke"
      client_key: "0pLxbN83FrOl5Nd0Fh9Zi5BQlMxSL2n5"
      client_secret: "YzuGNoJxeub8ZC6d"
      pass_key: "bfb279f9aa9bdbcf158e97dd71a467cd2e0c893059b10f78e6b72ada1ed2c919"
    roster:
      name: "roster"
      business_short_code: "7385028"
      till: "1234567"
      auth_host: "https://sandbox.safaricom.co.ke/oauth/v1/generate"
      api_host: "https://sandbox.safaricom.co.ke"
      client_key: "0pLxbN83FrOl5Nd0Fh9Zi5BQlMxSL2n5"
      client_secret: "YzuGNoJxeub8ZC6d"
      pass_key: "bfb279f9aa9bdbcf158e97dd71a467cd2e0c893059b10f78e6b72ada1ed2c919"
    paygops:
      name: "paygops"
      business_short_code: "174379"
      till: "9347335"
      auth_host: "https://sandbox.safaricom.co.ke/oauth/v1/generate"
      api_host: "https://sandbox.safaricom.co.ke"
      client_key: "0pLxbN83FrOl5Nd0Fh9Zi5BQlMxSL2n5"
      client_secret: "YzuGNoJxeub8ZC6d"
      pass_key: "bfb279f9aa9bdbcf158e97dd71a467cd2e0c893059b10f78e6b72ada1ed2c919"
  limits:
    memory: "512M"
    cpu: "500m"
  requests:
    memory: "512M"
    cpu: "100m"
  ingress:
    enabled: false
    path: "/mpesa"
    annotations: {}
    backend: {}
  deployment:
    annotations: {}

roster_connector:
  enabled: false
  replicas: 1
  image: ""
  imageTag: "v1.0.1"
  imagePullPolicy: "Always"
  LOGGING_LEVEL_ROOT: "INFO"
  SPRING_PROFILES_ACTIVE: ""
  containerPort: 5000
  limits:
    memory: "512M"
    cpu: "500m"
  requests:
    memory: "512M"
    cpu: "100m"
  ams:
    local:
      enabled: ""
  pesacore:
    auth_header: ""
  deployment:
    annotations: {}

paygops_connector:
  enabled: false
  replicas: 1
  image: ""
  imageTag: "v1.0.1"
  imagePullPolicy: "Always"
  SPRING_PROFILES_ACTIVE: ""
  LOGGING_LEVEL_ROOT: "INFO"
  containerPort: 5000
  limits:
    memory: "512M"
    cpu: "500m"
  requests:
    memory: "256M"
    cpu: "50m"
  ams:
    local:
      enabled: ""
  paygops:
    authheader: ""
  deployment:
    annotations: {}

messagegateway:
  enabled: false
  replicas: 1
  image: ""
  imageTag: "v1.0.0"
  imagePullPolicy: "Always"
  LOGGING_LEVEL_ROOT: "INFO"
  hostname: ""
  CALLBACKCONFIG_HOST: "ph-ee-connector-notifications"
  HOSTCONFIG_HOST: "message-gateway"
  MYSQL_USERNAME: "mifos"
  MYSQL_PASSWORD: "password"
  DATASOURCE_URL: jdbc:mysql:thin://operationsmysql:3306/messagegateway
  PROVIDERSOURCE_FROMDATABASE: "disabled"
  PROVIDERSOURCE_FROMYML: "enabled"
  limits:
    memory: "512M"
    cpu: "500m"
  requests:
    memory: "512M"
    cpu: "100m"
  ingress:
    enabled: false
    path: "/messages"
    annotations: {}
    backend: {}
  secret:
    name: ""
    key:
      telerivet_api_key: ""
  deployment:
    annotations: {}

notifications:
  enabled: false
  replicas: 1
  image: ""
  imageTag: "v1.0.1"
  imagePullPolicy: "Always"
  SPRING_PROFILES_ACTIVE: ""
  LOGGING_LEVEL_ROOT: "INFO"
  hostname: ""
  zeebe_broker_contactpoint: "zeebe-zeebe-gateway:26500"
  MESSAGEGATEWAYCONFIG_HOST: "message-gateway"
  NOTIFICATION_LOCAL_HOST: "ph-ee-connector-notifications"
  NOTIFICATION_SUCCESS_ENABLED: "false"
  NOTIFICATION_FAILURE_ENABLED: "true"
  hostconfig:
    host: ""
    port: ""
  limits:
    memory: "512M"
    cpu: "500m"
  requests:
    memory: "512M"
    cpu: "100m"
  ingress:
    enabled: false
    path: "/notifications"
    annotations: {}
    backend: {}
  deployment:
    annotations: {}

zeebe_ops:
  enabled: true
  replicas: 1
  image: ""
  imageTag: "v1.0.1"
  imagePullPolicy: "Always"
  SPRING_PROFILES_ACTIVE: ""
  LOGGING_LEVEL_ROOT: "INFO"
  hostname: ""
  zeebe_broker_contactpoint: "zeebe-zeebe-gateway:26500"
  elasticsearch_contactpoint: "ph-ee-elasticsearch:9200"
  tenants: ""
  limits:
    memory: "512M"
    cpu: "500m"
  requests:
    memory: "512M"
    cpu: "100m"
  ingress:
    enabled: false
    path: "/zeebeops"
    annotations: {}
    backend: {}
  deployment:
    annotations: {}

importer_es:
  enabled: true
  replicas: 1
  image: ""
  imageTag: "v1.1.4"
  imagePullPolicy: "Always"
  reporting:
    enabled: false
  logging:
    level:
      root: "INFO"
  limits:
    memory: "512M"
    cpu: "500m"
  requests:
    memory: "512M"
    cpu: "100m"

kafka:
  enabled: true
  replicas: 1
  image: "spotify/kafka"
  imagePullPolicy: "Always"
  advertised:
      host: "kafka"
      port: "9092"
  limits:
    memory: "512M"
    cpu: "500m"
  requests:
    memory: "512M"
    cpu: "100m"
  deployment:
      annotations:
        deployTime: "{{ .Values.deployTime }}"

importer_rdbms:
  enabled: true
  replicas: 1
  image: ""
  imageTag: "v1.0.3"
  imagePullPolicy: "Always"
  LOGGING_LEVEL_ROOT: "INFO"
  datasource:
      username: "mifos"
      password: "password"
      host: "operationsmysql"
      port: 3306
      schema: "tenants"
  limits:
    memory: "512M"
    cpu: "500m"
  requests:
    memory: "512M"
    cpu: "100m"
  deployment:
    annotations: {}

connector_bulk:
  enabled: false
  replicas: 1
  image: ""
  imageTag: "v1.0.0"
  imagePullPolicy: "Always"
  SPRING_PROFILES_ACTIVE: ""
  limits:
    memory: "512M"
    cpu: "500m"
  requests:
    memory: "512M"
    cpu: "100m"
  deployment:
    annotations: {}

ph_ee_connector_gsma:
  enabled: false
  replicas: 1
  image: ""
  imageTag: "v1.0.0"
  imagePullPolicy: "Always"
  SPRING_PROFILES_ACTIVE: ""
  limits:
    memory: "512M"
    cpu: "500m"
  requests:
    memory: "512M"
    cpu: "100m"
  deployment:
    annotations: {}

ph_ee_connector_slcb:
  enabled: false
  replicas: 1
  image: ""
  imagePullPolicy: "Always"
  SPRING_PROFILES_ACTIVE: ""
  limits:
    memory: "512M"
    cpu: "500m"
  requests:
    memory: "512M"
    cpu: "100m"
  deployment:
    annotations: {}

wildcardhostname: ""

tls: ""
