apiVersion: apps/v1
kind: Deployment
metadata:
  name: "ph-ee-connector-ams-pesa"
  labels:
    app: ph-ee-connector-ams-pesa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ph-ee-connector-ams-pesa
  template:
    metadata:
      labels:
        app: ph-ee-connector-ams-pesa
      annotations:
        deployTime: "{{ .Values.deployTime }}"
    spec:
      containers:
        - name: ph-ee-connector-ams-pesa
          image: "{{ .Values.roster_connector.image }}"
          ports:
            - containerPort: 5000
          resources:
            limits:
              memory: "400M"
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 9191
            initialDelaySeconds: 120
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 9191
            initialDelaySeconds: 120
            periodSeconds: 30
          env:
            - name: "SPRING_PROFILES_ACTIVE"
              value: "{{ .Values.roster_connector.SPRING_PROFILES_ACTIVE }}"
            - name: "ZEEBE_BROKER_CONTACTPOINT"
              value: "zeebe-zeebe-gateway:26500"