apiVersion: apps/v1
kind: Deployment
metadata:
  name: "ph-ee-connector-notifications"
  labels:
    app: ph-ee-connector-notifications
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ph-ee-connector-notifications
  template:
    metadata:
      labels:
        app: ph-ee-connector-notifications
      annotations:
        deployTime: "{{ .Values.deployTime }}"
    spec:
      containers:
        - name: ph-ee-connector-notifications
          image: "{{ .Values.notifications.image }}"
          ports:
           - containerPort: 5000
          resources:
            limits:
              memory: "512M"
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 9191
            initialDelaySeconds: 120
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 9191
            initialDelaySeconds: 120
            periodSeconds: 30
          env:
            - name: "SPRING_PROFILES_ACTIVE"
              value: "{{ .Values.notifications.SPRING_PROFILES_ACTIVE }}"
            - name: "ZEEBE_BROKER_CONTACTPOINT"
              value: "zeebe-zeebe-gateway:26500"
            - name: "HOSTCONFIG_HOST"
              value: "message-gateway"
            - name: "HOSTCONFIG_PORT"
              value: "80"
            - name: "MESSAGEGATEWAYCONFIG_HOST"
              value: "{{ .Values.notifications.MESSAGEGATEWAYCONFIG_HOST }}"
            - name: "NOTIFICATION_LOCAL_HOST"
              value: "{{ .Values.notifications.NOTIFICATION_LOCAL_HOST }}"

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ph-ee-connector-notifications
  name: ph-ee-connector-notifications
spec:
  ports:
    - name: port
      port: 80
      protocol: TCP
      targetPort: 5000
  selector:
    app: ph-ee-connector-notifications
  sessionAffinity: None
  type: ClusterIP
