apiVersion: apps/v1
kind: Deployment
metadata:
  name: "ph-ee-connector-channel"
  labels:
    app: ph-ee-connector-channel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ph-ee-connector-channel
  template:
    metadata:
      labels:
        app: ph-ee-connector-channel
      annotations:
        deployTime: "{{ .Values.deployTime }}"
    spec:
      containers:
        - name: ph-ee-connector-channel
          image: "{{ .Values.channel.image }}" 
          ports:
            - containerPort: 5000
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 30
          env:
            - name: "SPRING_PROFILES_ACTIVE"
              value: "{{ .Values.channel.SPRING_PROFILES_ACTIVE }}"
          volumeMounts:
            - name: ph-ee-config
              mountPath: "/config"
          resources:
            limits:
              memory: "650M"
      volumes:
        - name: ph-ee-config
          configMap:
            name: ph-ee-config

---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ph-ee-connector-channel
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: "{{ .Values.channel.hostname }}"
      http:
        paths:
        - backend:
            serviceName: ph-ee-connector-channel
            servicePort: 80

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ph-ee-connector-channel
  name: ph-ee-connector-channel
spec:
  ports:
    - name: port
      port: 80
      protocol: TCP
      targetPort: 5000
  selector:
    app: ph-ee-connector-channel
  sessionAffinity: None
  type: ClusterIP
