{{- if .Values.channel.enabled -}}

apiVersion: {{ .Values.deployment.apiversion }}
kind: Deployment
metadata:
  name: "ph-ee-connector-channel"
  labels:
    app: ph-ee-connector-channel
spec:
  replicas: {{ .Values.channel.replicas }}
  selector:
    matchLabels:
      app: ph-ee-connector-channel
  template:
    metadata:
      labels:
        app: ph-ee-connector-channel
      annotations:
{{- if .Values.channel.deployment.annotations }}
{{ toYaml .Values.channel.deployment.annotations | indent 8 }}
{{- end }}
    spec:
      containers:
        - name: ph-ee-connector-channel
          image: "{{ .Values.channel.image }}:{{ .Values.channel.imageTag }}"
          ports:
            - containerPort: 5000
          imagePullPolicy: "{{ .Values.channel.imagePullPolicy }}"
          resources:
            limits:
              memory: "{{ .Values.channel.limits.memory }}"
              cpu: "{{ .Values.channel.limits.cpu }}"
            requests:
              memory: "{{ .Values.channel.requests.memory }}"
              cpu: "{{ .Values.channel.requests.cpu }}"
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 30
          env:
            - name: "spring_profiles_active"
              value: "{{ .Values.channel.springProfilesActive }}"
            - name: "dfspids"
              value: "{{ .Values.channel.dfspid }}"
            - name: "transaction-id-length"
              value: "{{ .Values.channel.transactionIdLength }}"
            - name: "mpesa_notification_success_enabled"
              value: "{{ .Values.notifications.notificationSuccessEnabled }}"
            - name: "mpesa_notification_failure_enabled"
              value: "{{ .Values.notifications.notificationFailureEnabled }}"
            - name:  "logging_level_root"
              value: "{{ .Values.channel.loggingLevelRoot }}"
            - name: "ams"
              value: "{{ .Values.channel.ams }}"
          volumeMounts:
            - name: ph-ee-config
              mountPath: "/config"
      volumes:
        - name: ph-ee-config
          configMap:
            name: ph-ee-config

---
{{- if .Values.channel.ingress.enabled }}
apiVersion: {{ .Values.ingress.apiversion }}
kind: Ingress
metadata:
  name: ph-ee-connector-channel
  annotations:
{{- if .Values.channel.ingress.annotations }}
{{ toYaml .Values.channel.ingress.annotations | indent 4 }}
{{- end }}
spec:
  rules:
    - host: "{{ .Values.channel.hostname }}"
      http:
        paths:
        - path: "{{ .Values.channel.ingress.path }}"
          pathType: Prefix
          backend:
{{- if .Values.channel.ingress.backend }}
{{ toYaml .Values.channel.ingress.backend | indent 14 }}
{{- end }}

  tls:
    - hosts:
        - "{{ .Values.wildcardhostname }}"
      secretName: "{{ .Values.tls }}"
{{- end }}

---
apiVersion: {{ .Values.service.apiversion }}
kind: Service
metadata:
  labels:
    app: ph-ee-connector-channel
  name: ph-ee-connector-channel
spec:
  ports:
    - name: port
      port: 80
      protocol: TCP
      targetPort: 5000
  selector:
    app: ph-ee-connector-channel
  sessionAffinity: None
  type: ClusterIP

  {{- end }}