{{- if .Values.connector_bulk.enabled -}}

apiVersion: {{ .Values.deployment.apiversion }}
kind: Deployment
metadata:
  name: "ph-ee-connector-bulk"
  labels:
    app: ph-ee-connector-bulk
spec:
  replicas: {{ .Values.connector_bulk.replicas }}
  selector:
    matchLabels:
      app: ph-ee-connector-bulk
  template:
    metadata:
      labels:
        app: ph-ee-connector-bulk
      annotations:
{{- if .Values.connector_bulk.deployment.annotations }}
{{ toYaml .Values.connector_bulk.deployment.annotations | indent 8 }}
{{- end }}
    spec:
      containers:
        - name: ph-ee-connector-bulk
          image: "{{ .Values.connector_bulk.image }}:{{ .Values.connector_bulk.imageTag }}"
          imagePullPolicy: "{{ .Values.connector_bulk.imagePullPolicy }}"
          ports:
            - containerPort: 5000
          resources:
            limits:
              memory: "{{ .Values.connector_bulk.limits.memory }}"
              cpu: "{{ .Values.connector_bulk.limits.cpu }}"
            requests:
              memory: "{{ .Values.connector_bulk.requests.memory }}"
              cpu: "{{ .Values.connector_bulk.requests.cpu }}"
          env:
            - name: "SPRING_PROFILES_ACTIVE"
              value: "{{ .Values.connector_bulk.SPRING_PROFILES_ACTIVE }}"
          volumeMounts:
            - name: ph-ee-config
              mountPath: "/config"
      volumes:
        - name: ph-ee-config
          configMap:
            name: ph-ee-config

---
apiVersion: {{ .Values.service.apiversion }}
kind: Service
metadata:
  labels:
    app: ph-ee-connector-bulk
  name: ph-ee-connector-bulk
  namespace: default
spec:
  ports:
    - name: port
      port: 80
      protocol: TCP
      targetPort: 5000
  selector:
    app: ph-ee-connector-bulk
  sessionAffinity: None
  type: ClusterIP

{{- end }}

---
{{- if .Values.connector_bulk.ingress.enabled }}
apiVersion: {{ .Values.ingress.apiversion }}
kind: Ingress
metadata:
  name: ph-ee-connector-bulk
  annotations:
{{- if .Values.connector_bulk.ingress.annotations }}
{{ toYaml .Values.connector_bulk.ingress.annotations | indent 4 }}
{{- end }}
spec:
  rules:
    - host: "{{ .Values.connector_bulk.hostname }}"
      http:
        paths:
        - path: "{{ .Values.connector_bulk.ingress.path }}"
          pathType: Prefix
          backend:
{{- if .Values.connector_bulk.ingress.backend }}
{{ toYaml .Values.connector_bulk.ingress.backend | indent 14 }}
{{- end }}

  tls:
    - hosts:
        - "{{ .Values.wildcardhostname }}"
      secretName: "{{ .Values.tls }}"
{{- end }}
