{{- if .Values.mpesa.enabled -}}

apiVersion: {{ .Values.deployment.apiversion }}
kind: Deployment
metadata:
  name: "ph-ee-connector-mpesa"
  labels:
    app: ph-ee-connector-mpesa
spec:
  replicas: {{ .Values.mpesa.replicas }}
  selector:
    matchLabels:
      app: ph-ee-connector-mpesa
  template:
    metadata:
      labels:
        app: ph-ee-connector-mpesa
      annotations:
{{- if .Values.mpesa.deployment.annotations }}
{{ toYaml .Values.mpesa.deployment.annotations | indent 8 }}
{{- end }}
    spec:
      containers:
        - name: ph-ee-connector-mpesa
          image: "{{ .Values.mpesa.image }}:{{ .Values.mpesa.imageTag }}"
          ports:
            - containerPort: 5000
          imagePullPolicy: "{{ .Values.mpesa.imagePullPolicy }}"
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 30
          resources:
            limits:
              memory: "{{ .Values.mpesa.limits.memory }}"
              cpu: "{{ .Values.mpesa.limits.cpu }}"
            requests:
              memory: "{{ .Values.mpesa.requests.memory }}"
              cpu: "{{ .Values.mpesa.requests.cpu }}"
          env:
            - name: "spring_profiles_active"
              value: "{{ .Values.mpesa.springProfilesActive }}"
            - name: "zeebe_broker_contactpoint"
              value: "{{ .Values.mpesa.zeebeBrokerContactpoint }}"
            - name: "mpesa_local_host"
              value: "{{ .Values.mpesa.callbackHost }}"
            - name: "mpesa_api_timeout"
              value: "{{ .Values.mpesa.apiTimeout }}"
            - name: "mpesa_max-retry-count"
              value: "{{ .Values.mpesa.retryCount }}"
            - name: "tenant"
              value: "{{ .Values.mpesa.tenant }}"
            - name: "logging_level_root"
              value:  "{{ .Values.mpesa.loggingLevelRoot }}"
            - name: "accounts_roster_shortcode"
              value: "{{ .Values.mpesa.accounts.roster.businessShortCode }}"
            - name: "accounts_roster_till"
              value: "{{ .Values.mpesa.accounts.roster.till }}"
            - name: "accounts_roster_authhost"
              value: "{{ .Values.mpesa.accounts.roster.authHost }}"
            - name: "accounts_roster_apihost"
              value: "{{ .Values.mpesa.accounts.roster.apiHost }}"
            - name: "accounts_roster_clientkey"
              valueFrom:
                secretKeyRef:
                  name: "mpesa-secret-roster"
                  key: "client-key"
            - name: "accounts_roster_clientsecret"
              valueFrom:
                secretKeyRef:
                  name: "mpesa-secret-roster"
                  key: "client-secret"
            - name: "accounts_roster_passkey"
              valueFrom:
                secretKeyRef:
                  name: "mpesa-secret-roster"
                  key: "pass-key"
            - name: "accounts_paygops_shortcode"
              value: "{{ .Values.mpesa.accounts.paygops.businessShortCode}}"
            - name: "accounts_paygops_till"
              value: "{{ .Values.mpesa.accounts.paygops.till }}"
            - name: "accounts_paygops_authhost"
              value: "{{ .Values.mpesa.accounts.paygops.authHost }}"
            - name: "accounts_paygops_apihost"
              value: "{{ .Values.mpesa.accounts.paygops.apiHost }}"
            - name: "accounts_paygops_clientkey"
              valueFrom:
                secretKeyRef:
                  name: "mpesa-secret-paygops"
                  key: "client-key"
            - name: "accounts_paygops_clientsecret"
              valueFrom:
                secretKeyRef:
                  name: "mpesa-secret-paygops"
                  key: "client-secret"
            - name: "accounts_paygops_passkey"
              valueFrom:
                secretKeyRef:
                  name: "mpesa-secret-paygops"
                  key: "pass-key"
            - name: "skip_enabled"
              value: "{{ .Values.mpesa.skip.enabled }}"


---
apiVersion: {{ .Values.service.apiversion }}
kind: Service
metadata:
  labels:
    app: ph-ee-connector-mpesa
  name: ph-ee-connector-mpesa
spec:
  ports:
    - name: port
      port: 80
      protocol: TCP
      targetPort: 5000
  selector:
    app: ph-ee-connector-mpesa
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: {{ .Values.secret.apiversion }}
kind: Secret
metadata:
  name: mpesa-secret-roster
type: Opaque
data:
  client-key: {{ .Values.mpesa.accounts.roster.clientKey | b64enc }}
  client-secret: {{ .Values.mpesa.accounts.roster.clientSecret | b64enc }}
  pass-key: {{ .Values.mpesa.accounts.roster.passKey | b64enc }}

---
apiVersion: {{ .Values.secret.apiversion }}
kind: Secret
metadata:
  name: mpesa-secret-paygops
type: Opaque
data:
  client-key: {{ .Values.mpesa.accounts.paygops.clientKey | b64enc }}
  client-secret: {{ .Values.mpesa.accounts.paygops.clientSecret | b64enc }}
  pass-key: {{ .Values.mpesa.accounts.paygops.passKey | b64enc }}

---
{{- if .Values.mpesa.ingress.enabled }}
apiVersion: {{ .Values.ingress.apiversion }}
kind: Ingress
metadata:
  name: ph-ee-connector-mpesa
  annotations:
{{- if .Values.mpesa.ingress.annotations }}
{{ toYaml .Values.mpesa.ingress.annotations | indent 4 }}
{{- end }}

spec:
  rules:
    - host: "{{ .Values.mpesa.hostname }}"
      http:
        paths:
          - path: "{{ .Values.mpesa.ingress.path }}"
            pathType: Prefix
            backend:
{{- if .Values.mpesa.ingress.backend }}
{{ toYaml .Values.mpesa.ingress.backend | indent 14 }}
{{- end }}

  tls:
    - hosts:
        - "{{ .Values.wildcardhostname }}"
      secretName: "{{ .Values.tls }}"
{{- end }}

{{- end }}
