{{- if .Values.mpesa.enabled -}}

apiVersion: {{ .Values.deployment.apiversion }}
kind: Deployment
metadata:
  name: "ph-ee-connector-notifications"
  labels:
    app: ph-ee-connector-notifications
spec:
  replicas: {{ .Values.notifications.replicas }}
  selector:
    matchLabels:
      app: ph-ee-connector-notifications
  template:
    metadata:
      labels:
        app: ph-ee-connector-notifications
      annotations:
{{- if .Values.notifications.deployment.annotations }}
{{ toYaml .Values.notifications.deployment.annotations | indent 8 }}
{{- end }}
    spec:
      containers:
        - name: ph-ee-connector-notifications
          image: "{{ .Values.notifications.image }}:{{ .Values.notifications.imageTag }}"
          imagePullPolicy: "{{ .Values.notifications.imagePullPolicy }}"
          resources:
            limits:
              memory: "{{ .Values.notifications.limits.memory }}"
              cpu: "{{ .Values.notifications.limits.cpu }}"
            requests:
              memory: "{{ .Values.notifications.requests.memory }}"
              cpu: "{{ .Values.notifications.requests.cpu }}"
          ports:
           - containerPort: 5000
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 30
          env:
            - name: "spring_profiles_active"
              value: "{{ .Values.notifications.springProfilesActive }}"
            - name: "zeebe_broker_contactpoint"
              value: "{{ .Values.notifications.zeebeBrokerContactpoint }}"
            - name: "hostconfig_host"
              value: "{{ .Values.notifications.hostconfig.host }}"
            - name: "hostconfig_port"
              value: "{{ .Values.notifications.hostconfig.port }}"
            - name: "messagegatewayconfig_host"
              value: "{{ .Values.notifications.messagegatewayconfigHost }}"
            - name: "notification_local_host"
              value: "{{ .Values.notifications.notificationLocalHost }}"
            - name: "notification_success_enabled"
              value: "{{ .Values.notifications.notificationSuccessEnabled }}"
            - name: "notification_failure_enabled"
              value: "{{ .Values.notifications.notificationFailureEnabled }}"
            - name: "logging_level_root"
              value:  "{{ .Values.notifications.loggingLevelRoot }}"

---
apiVersion: {{ .Values.service.apiversion }}
kind: Service
metadata:
  labels:
    app: ph-ee-connector-notifications
  name: ph-ee-connector-notifications
spec:
  ports:
    - name: port
      port: 80
      protocol: TCP
      targetPort: 5000
  selector:
    app: ph-ee-connector-notifications
  sessionAffinity: None
  type: ClusterIP


---
{{- if .Values.notifications.ingress.enabled }}
apiVersion: {{ .Values.ingress.apiversion }}
kind: Ingress
metadata:
  name: ph-ee-notifications
  annotations:
{{- if .Values.notifications.ingress.annotations }}
{{ toYaml .Values.notifications.ingress.annotations | indent 4 }}
{{- end }}
spec:
  rules:
    - host: "{{ .Values.notifications.hostname }}"
      http:
        paths:
          - path: "{{ .Values.notifications.ingress.path }}"
            pathType: Prefix
            backend:
{{- if .Values.notifications.ingress.backend }}
{{ toYaml .Values.notifications.ingress.backend | indent 14 }}
{{- end }} 

  tls:
    - hosts:
        - "{{ .Values.wildcardhostname }}"
      secretName: "{{ .Values.tls }}"
{{- end }}

{{- end }}