{{- if .Values.connector_bulk.enabled -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: "ph-ee-connector-bulk"
  labels:
    app: ph-ee-connector-bulk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ph-ee-connector-bulk
  template:
    metadata:
      labels:
        app: ph-ee-connector-bulk
      annotations:
{{- if .Values.connector_bulk.deployment.annotations }}
{{ toYaml .Values.connector_bulk.deployment.annotations | indent 8 }}
{{- end }}
    spec:
      containers:
        - name: ph-ee-connector-bulk
          image: us.icr.io/phee-ns/ph-ee-connector-bulk
          ports:
            - containerPort: 5000
          env:
            - name: "SPRING_PROFILES_ACTIVE"
              value: "{{ .Values.connector_bulk.SPRING_PROFILES_ACTIVE }}"
          volumeMounts:
            - name: ph-ee-config
              mountPath: "/config"
      volumes:
        - name: ph-ee-config
          configMap:
            name: ph-ee-config

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ph-ee-connector-bulk
  name: ph-ee-connector-bulk
  namespace: default
spec:
  ports:
    - name: port
      port: 80
      protocol: TCP
      targetPort: 5000
  selector:
    app: ph-ee-connector-bulk
  sessionAffinity: None
  type: ClusterIP

{{- end }}
