{{- if .Values.operations.enabled -}}

apiVersion: {{ .Values.deployment.apiversion }}
kind: Deployment
metadata:
  name: ph-ee-importer-es
  labels:
    app: ph-ee-importer-es
spec:
  replicas: {{ .Values.importer_es.replicas }}
  selector:
    matchLabels:
      app: ph-ee-importer-es
  template:
    metadata:
      labels:
        app: ph-ee-importer-es
    spec:
      containers:
        - name: ph-ee-importer-es
          image: "{{ .Values.importer_es.image }}:{{ .Values.importer_es.imageTag }}"
          imagePullPolicy: "{{ .Values.importer_es.imagePullPolicy }}"
          resources:
            limits:
              memory: "{{ .Values.importer_es.limits.memory }}"
              cpu: "{{ .Values.importer_es.limits.cpu }}"
            requests:
              memory: "{{ .Values.importer_es.requests.memory }}"
              cpu: "{{ .Values.importer_es.requests.cpu }}"
          env:
          - name: "reporting.enabled"
            value: "{{ .Values.importer_es.reporting.enabled }}"
          - name: "logging_level_ROOT"
            value: "{{ .Values.importer_es.logging.level.root }}"
          - name: "JAVA_TOOL_OPTIONS"
            value: "{{ .Values.importer_es.javaToolOptions}}"
          - name: "LOGGING_PATTERN_CONSOLE"
            value: "{{ .Values.importer_es.logging.pattern.console}}"
          - name: "ELASTICSEARCH_SECURITY_ENABLED"
            value: "{{ .Values.importer_es.elasticsearch_security_enabled }}"
          - name: "ELASTICSEARCH_SSLVERIFICATION"
            value: "{{ .Values.importer_es.elasticsearch_sslverification }}"
          - name: "ELASTICSEARCH_USERNAME"
            valueFrom:
              secretKeyRef:
                name: elastic-credentials
                key: username
          - name: "ELASTICSEARCH_PASSWORD"
            valueFrom:
              secretKeyRef:
                name: elastic-credentials
                key: password

{{- end }}
